const { CoachingSession } = require('../models');

const coachingData = [
  {
    start_time: Date.now(),
    location: 'Perth',
    duration: 2,
    topic: 'Pre-start meeting',
    complete: true,
    signedOff: false,
    senior_coordinator_id: 3,
    supervisor_id: 6,
    superintendent_id: 1,
  },
  {
    start_time: Date.now(),
    location: 'Woolgorong',
    duration: 4,
    topic: 'LiF meeting',
    complete: true,
    signedOff: true,
    senior_coordinator_id: 4,
    supervisor_id: 7,
    superintendent_id: null,
  },
  {
    start_time: Date.now(),
    location: 'Broome',
    duration: 1,
    topic: 'Pre-task hazard assessment',
    complete: true,
    signedOff: false,
    senior_coordinator_id: 5,
    supervisor_id: 8,
    superintendent_id: 2,
  },
  {
    start_time: Date.now(),
    location: 'Bunbury',
    duration: 5,
    topic: 'Critical risk management',
    complete: true,
    signedOff: true,
    senior_coordinator_id: 3,
    supervisor_id: 9,
    superintendent_id: null,
  },
  {
    start_time: Date.now(),
    location: 'Derby',
    duration: 3,
    topic: 'Quality Safety interaction',
    complete: true,
    signedOff: false,
    senior_coordinator_id: 4,
    supervisor_id: 10,
    superintendent_id: null,
  },
  {
    start_time: Date.now(),
    location: 'Ulladulla',
    duration: 2,
    topic: 'Safety spotlight',
    complete: true,
    signedOff: true,
    senior_coordinator_id: 5,
    supervisor_id: 6,
    superintendent_id: 1,
  },
  {
    start_time: Date.now(),
    location: 'Singleton',
    duration: 1,
    topic: 'Pre-start meeting',
    complete: true,
    signedOff: true,
    senior_coordinator_id: 3,
    supervisor_id: 7,
    superintendent_id: 2,
  },
  {
    start_time: Date.now(),
    location: 'Mount Barker',
    duration: 2,
    topic: 'Leadership in the Field',
    complete: false,
    signedOff: false,
    senior_coordinator_id: 3,
    supervisor_id: 8,
    superintendent_id: null,
  },
  {
    start_time: Date.now(),
    location: 'Coolgardie',
    duration: 4,
    topic: 'Pre-task hazard assessment',
    complete: false,
    signedOff: false,
    senior_coordinator_id: 5,
    supervisor_id: 10,
    superintendent_id: 1,
  },
  {
    start_time: Date.now(),
    location: 'Kwinana',
    duration: 3,
    topic: 'Critical risk management',
    complete: false,
    signedOff: false,
    senior_coordinator_id: 5,
    supervisor_id: 6,
    superintendent_id: null,
  },
  {
    start_time: Date.now(),
    location: 'Busselton',
    duration: 2,
    topic: 'Quality Safety interaction',
    complete: false,
    signedOff: false,
    senior_coordinator_id: 4,
    supervisor_id: 6,
    superintendent_id: null,
  },
  {
    start_time: Date.now(),
    location: 'Port Hedland',
    duration: 1,
    topic: 'Safety spotlight',
    complete: false,
    signedOff: false,
    senior_coordinator_id: 3,
    supervisor_id: 10,
    superintendent_id: 2,
  },
  {
    start_time: Date.now(),
    location: 'Mandurah',
    duration: 1,
    topic: 'Pre-start meeting',
    complete: false,
    signedOff: false,
    senior_coordinator_id: 5,
    supervisor_id: 7,
    superintendent_id: 2,
  },
  {
    start_time: Date.now(),
    location: 'Newman',
    duration: 5,
    topic: 'Leadership in the Field',
    complete: false,
    signedOff: false,
    senior_coordinator_id: 4,
    supervisor_id: 6,
    superintendent_id: null,
  },
  {
    start_time: Date.now(),
    location: 'Tom Price',
    duration: 3,
    topic: 'Pre-task hazard assessment',
    complete: false,
    signedOff: false,
    senior_coordinator_id: 4,
    supervisor_id: 10,
    superintendent_id: 1,
  },
];

const seedCoachingData = async () => {
  await CoachingSession.bulkCreate(coachingData, {
    individualHooks: true,
  });
};

module.exports = seedCoachingData;
